// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qsyycuoutrlqmokvpzqz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFzeXljdW91dHJscW1va3ZwenF6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3NTg3OTEsImV4cCI6MjA1OTMzNDc5MX0.gouuW0AdJc0fqPmX8HCxEBSX3N6I3J8ipfEFxdXbJgg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);